"""Initiall migration

Revision ID: 4d56aae14c0f
Revises: 
Create Date: 2024-11-17 18:57:44.708053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d56aae14c0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_slug', table_name='products')
    op.drop_column('products', 'slug')
    op.drop_index('ix_users_slug', table_name='users')
    op.drop_column('users', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slug', sa.VARCHAR(), nullable=True))
    op.create_index('ix_users_slug', 'users', ['slug'], unique=1)
    op.add_column('products', sa.Column('slug', sa.VARCHAR(), nullable=True))
    op.create_index('ix_products_slug', 'products', ['slug'], unique=1)
    # ### end Alembic commands ###
